[phases.setup]
nixPkgs = [
    "python311",
    "python311Packages.poetry"
]

[phases.install]
cmds = [
    "cd backend",
    "poetry install --no-interaction --no-ansi"
]

[start]
cmd = "cd backend && poetry run uvicorn main:app --host 0.0.0.0 --port $PORT" 