[phases.setup]
nixPkgs = [
    "python311",
    "python311Packages.pip",
    "python311Packages.fastapi",
    "python311Packages.uvicorn",
    "python311Packages.python-dotenv",
    "python311Packages.supabase",
    "python311Packages.python-jose",
    "python311Packages.passlib",
    "python311Packages.python-multipart",
    "python311Packages.httpx",
    "python311Packages.pydantic",
    "python311Packages.openai",
    "python311Packages.langchain",
    "python311Packages.langchain-openai",
    "python311Packages.langchain-community",
    "python311Packages.langchain-core"
]

[phases.install]
cmds = []

[start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT" 