[phases.setup]
nixPkgs = [
    "python311",
    "poetry",
    "python311Packages.pip"
]

[phases.install]
cmds = [
    "cd /app/backend",
    "poetry config virtualenvs.create false",
    "poetry install --no-interaction --no-ansi --no-root"
]

[start]
cmd = "cd /app/backend && poetry run uvicorn main:app --host 0.0.0.0 --port $PORT" 