[phases.setup]
nixPkgs = [
    "python311",
    "poetry"
]

[phases.install]
cmds = [
    "cd /app",
    "poetry config virtualenvs.create false",
    "poetry install --no-interaction --no-ansi"
]

[start]
cmd = "cd /app && poetry run uvicorn backend.main:app --host 0.0.0.0 --port $PORT" 