[phases.setup]
nixPkgs = [
    "python311",
    "poetry"
]

[phases.install]
cmds = [
    "cp -r backend/* /app/",
    "cd /app",
    "poetry config virtualenvs.create false",
    "poetry install --no-interaction --no-ansi"
]

[phases.build]
cmds = [
    "cd /app",
    "poetry build"
]

[start]
cmd = "cd /app && poetry run uvicorn main:app --host 0.0.0.0 --port $PORT"

[build]
dockerfile = "backend/Dockerfile" 