[build]
builder = "nixpacks"
buildCommand = "poetry install --no-interaction --no-ansi --no-root"

[deploy]
startCommand = "cd /app/backend && PYTHONPATH=. poetry run uvicorn main:app --host 0.0.0.0 --port $PORT" 