[build]
builder = "nixpacks"
buildCommand = "cd backend && poetry install --no-interaction --no-ansi --no-root"

[deploy]
startCommand = "cd /app/backend && PYTHONPATH=/app/backend poetry run uvicorn main:app --host 0.0.0.0 --port $PORT" 