[build]
builder = "nixpacks"
buildCommand = "poetry install --no-interaction --no-ansi --no-root"

[deploy]
startCommand = "cd /app && PYTHONPATH=/app poetry run uvicorn backend.main:app --host 0.0.0.0 --port $PORT" 