[build]
builder = "nixpacks"
buildCommand = "cd backend && poetry install --no-interaction --no-ansi --no-root"

[deploy]
startCommand = "cd /app && PYTHONPATH=/app poetry run python -c 'from backend.main import app; import uvicorn; uvicorn.run(app, host=\"0.0.0.0\", port=int(\"$PORT\"))'" 