[build]
builder = "nixpacks"
buildCommand = "cd backend && poetry install --no-interaction --no-ansi --no-root && cd .. && pip install -e ."

[deploy]
startCommand = "cd /app && PYTHONPATH=/app poetry run uvicorn backend.main:app --host 0.0.0.0 --port $PORT" 